### ISSUE TITLE
How to translate to Chinese language?

### ISSUE THREAD

**Issue by xuegoo** [Pylo/MinecraftLink#2]
We are maker teachers in China.We love your software,but we cannot find Chinese language for kids.Hope to get supported.or give us some information how to translate.Thanks

**Comment by KlemenDEV** [comment]
If you are talking about Minecraft Link mod interface, the translation files can be found in this directory: https://github.com/Pylo/MinecraftLink/tree/master/src/main/resources/assets/minecraft_link/lang If you make translation feel free to submit pull request so we add it to master repo.

If you are asking about the translation of MCreator, check this issue on our MCreator issue tracker: https://mcreator.net/tracker/issue/41284
